#!/bin/bash -e

echo "$GITHUB_REMOTE_SSH_KEY" > /home/$USERNAME/.ssh/id_ed25519
rsync -avz -e "ssh -p $GITHUB_REMOTE_SSH_PORT" /home/$USERNAME/repo/ $GITHUB_REMOTE_SSH_USER@$GITHUB_REMOTE_ADDR:$GITHUB_REMOTE_REPO